#!/bin/bash

set -euE -o pipefail

authority="rakastajienkilta@oiva.sange.fi"
destdir="./www"

websitedir="$(realpath "$(dirname "$0")")"
"${websitedir}/build

rsync --verbose --recursive --delete --perms --chmod="ug=rwX,o+rX" --times \
    "${websitedir}"/output/ "${authority}:${destdir}"
