#!/bin/bash

set -euE -o pipefail

authority="rakastajienkilta@oiva.sange.fi"
destdir="./www"

websitedir="$(realpath "$(dirname "$0")")"
rm -rf "${websitedir}/"{output,shake}
eval "${websitedir}/run-lovegen" -C "${websitedir}"

rsync --verbose --recursive --delete --perms --chmod="ug=rwX,o+rX" --times \
    "${websitedir}"/output/ "${authority}:${destdir}"
