#!/bin/bash

set -euE -o pipefail

authority="rakastajienkilta@oiva.sange.fi"
dest_dir="./www"

website_dir="$(realpath "$(dirname "$0")")"
"${website_dir}/build"

rsync --verbose --recursive --delete --perms --chmod="ug=rwX,o+rX" --times \
    "${website_dir}"/output/ "${authority}:${dest_dir}"
