title-suffix: Rakastajien kilta
indexing: true
keywords:
  - rakastajien kilta
  - tietoinen seksuaalisuus
    
lang: fi
template: page.html
strings:
  copyright-period: 2018–2022
  last-modified: Päivitetty
  site-author: Rakastajien kilta
  site-name: Rakastajien kilta
  table-of-contents: Sisällys

  cc:
    alt: [Creative Commons -lisenssin logo]
    license-pre: Tämän sivuston sisältö on lisensoitu
    license-name: Creative Commons Attribution-NonCommercial-ShareAlike 4.0 kansainvälisellä lisenssillä
    license-post: "\ aina, kun muuta ei ole mainittu."
