title-suffix: Rakastajien kilta

lang: fi
template: page.html
strings:
  copyright-period: 2018–2022
  last-modified: Viimeksi päivitetty
  site-author: Rakastajien kilta
  table-of-contents: Sisällys

  cc:
    alt: [Creative Commons -lisenssin logo]
    license-pre: Tämän sivuston sisältö on lisensoitu
    license-name: Creative Commons Attribution-ShareAlike 4.0 kansainvälisellä lisenssillä
    license-post: ", ellei muuta ole mainittu."
