title-suffix: Lovers' Guild
indexing: true
keywords:
  - conscious sexuality
  - Lovers' Guild
lang: en
template: page.html
strings:
  copyright-period: 2018–2023
  last-modified: Last updated
  logo-alt: Lovers' Guild's logo
  site-author: Lovers' Guild
  site-name: Lovers' Guild
  table-of-contents: Contents

  cc:
    alt: [Creative Commons License -logo]
    license-pre: Except where otherwise noted, content on this site is licensed under a
    license-name: Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License
    license-post: null
